### ISSUE TITLE
Error retrieving latest blog post

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#15]
Traceback:

KeyError: 'labels'
if "Change Logs" in post["labels"]:
File "/home/toconnell/kdm-manager/v1/utils.py", line 178, in get_latest_change_log
lcl = get_latest_change_log()["url"]
File "/home/toconnell/kdm-manager/v1/assets.py", line 325, in html_motd
Traceback (most recent call last):
[2016-08-17 13:03:47] ERROR:	An error occurred while trying to retrieve blog info!

**Comment by toconnell** [comment]
Fixed a bug in utils.py where blog posts without labels could cause the app to throw tracebacks while loading the dashboard.
