### ISSUE TITLE
v2 daemon controls need to NOT check for a PID file after stopping the daemon

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#155]
```
toconnell@ubuntu-trusty-1:~/kdm-manager/v2/api$ ./world.py -d stop
Traceback (most recent call last):
  File "./world.py", line 891, in <module>
    D.command(options.daemon_cmd)
  File "./world.py", line 753, in command
    self.dump_status()
  File "./world.py", line 838, in dump_status
    owner_uid = os.stat(self.pid_file_path).st_uid
OSError: [Errno 2] No such file or directory: '/home/toconnell/kdm-manager/v2/api/run/world_daemon.pid'
```

**Comment by toconnell** [comment]
Fixed this with an os.file.exists() check on self.pid_file_path
