### ISSUE TITLE
issue viewing a survivor

### ISSUE THREAD

**Issue by rkm262** [toconnell/kdm-manager#163]
When attempting to click on one of my survivors to see their details, I'm getting the following:

500 - Internal Server Error

Caught exception while rendering current view for rajeshkamalmehra@gmail.com (56906e5d421aa907a6f57ca9)!

Please report all issues at https://github.com/toconnell/kdm-manager/issues

Use the information below to report the error:

2016-11-30 06:21:31.261598

Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 495, in current_view_html
 output += S.render_html_form()
File "/home/toconnell/kdm-manager/v1/assets.py", line 2963, in render_html_form
 partners = self.get_intimacy_partners("html"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 1806, in get_intimacy_partners
 S = Survivor(survivor_id=s_id, session_object=self.Session)
File "/home/toconnell/kdm-manager/v1/assets.py", line 494, in __init__
 raise Exception("Invalid survivor ID: '%s'" % survivor_id)
Exception: Invalid survivor ID: '56c02ab1421aa92f76fc8697'

**Comment by toconnell** [comment]
Traceback makes this look like it's related to a removed survivor who can't be retrieved from the MDB. 

For now, we can get graceful Intimacy look-up failures for the Thursday/Friday release, I think.

Once this gets nailed down, complete #164 so that we don't have another one of these.

**Comment by toconnell** [comment]
Alright, I wrapped the list-building bit of assets.Survivor.get_intimacy_partners() in a little try/except and this fails gracefully now (and logs a warn with the exception):

```
[2016-11-30 08:34:20] ERROR:    Invalid survivor ID: '56c02ab1421aa92f76fc8697'
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v1/assets.py", line 1808, in get_intimacy_partners
    S = Survivor(survivor_id=s_id, session_object=self.Session)
  File "/home/toconnell/kdm-manager/v1/assets.py", line 494, in __init__
    raise Exception("Invalid survivor ID: '%s'" % survivor_id)
Exception: Invalid survivor ID: '56c02ab1421aa92f76fc8697'
[2016-11-30 08:34:20] WARNING:  [XXX (56906e5d421aa907a6f57ca9)] intimacy partner '56c02ab1421aa92f76fc8697' for Jeesh [M] could not be initialized!
```

This will go out in the next release.
