### ISSUE TITLE
Resurrect survivor - HTTP error 500

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#203]
Tried to resurrect a decapitated survivor and get 500:

2017-01-04 10:25:40.202848

Traceback:

Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 57, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 524, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 2626, in modify
 self.death(undo_death=True)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1068, in death
 self.logger.debug("[%s] is resurrecting '%s'" % self.survivor["name"])
TypeError: not enough arguments for format string

**Comment by toconnell** [comment]
This is basically a typo. I'm going to make sure and recreate it, I think, and then push a quick patch.

**Comment by toconnell** [comment]
This is resolved.
