### ISSUE TITLE
Investigate render failures where the API Asset cannot be retrieved.

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#205]
Two render failures in today over the automatic error emails.

I cannot reproduce them just by viewing the settlements (either as Settlement Sheets or as Campaign Summaries), but they each came in multiple times, so the users must be doing something that causes this.

Maybe they're clicking around faster than the API can respond? Let's look into a retry wrapper for the set_api_assets() and get_api_assets()  methods in the legacy app, maybe.

```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 466, in process_params
 S = assets.Settlement(settlement_id=s_id, session_object=self)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3183, in __init__
 self.set_settlement(settlement_id, update_mins)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3206, in set_settlement
 self.update_mins()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3239, in update_mins
 self.update_timeline_with_story_events()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3681, in update_timeline_with_story_events
 event = self.get_event(m_dict["story_event"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 3520, in get_event
 all_events = self.get_api_asset("game_assets","events")
File "/home/toconnell/kdm-manager/v1/assets.py", line 3296, in get_api_asset
 raise AttributeError(msg)
AttributeError: [holyword4446@gmail.com (585261b48740d965561d8ba8)] failed to initialize API asset for 'TEAGING' (58718a968740d95e60dcc28c)
```

```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 466, in process_params
 S = assets.Settlement(settlement_id=s_id, session_object=self)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3183, in __init__
 self.set_settlement(settlement_id, update_mins)
File "/home/toconnell/kdm-manager/v1/assets.py", line 3206, in set_settlement
 self.update_mins()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3239, in update_mins
 self.update_timeline_with_story_events()
File "/home/toconnell/kdm-manager/v1/assets.py", line 3681, in update_timeline_with_story_events
 event = self.get_event(m_dict["story_event"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 3520, in get_event
 all_events = self.get_api_asset("game_assets","events")
File "/home/toconnell/kdm-manager/v1/assets.py", line 3296, in get_api_asset
 raise AttributeError(msg)
AttributeError: [junk@lupissoft.com (5850c79f8740d9504f514ed3)] failed to initialize API asset for 'Last Light' (5872d0f48740d91a8852632b)
```

**Comment by toconnell** [comment]
Just added three retries with a modest wait/jitter. We'll see if these go away (or if we're logging retries or whatever). Leaving this open until I feel like it's resolved.

**Comment by toconnell** [comment]
I'm closing this: I haven't seen one of these since I fixed the bug preventing settlements/survivors from being removed, so I think my comment from eight days back was correct.
