### ISSUE TITLE
JS Quarry control failure

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#211]
From automatic render-failures email:

User _id: `5877eae38740d9700849e47d`

```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 545, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 5731, in modify
 self.update_quarries("add",game_asset_key)
File "/home/toconnell/kdm-manager/v1/assets.py", line 5230, in update_quarries
 m = self.get_api_asset("game_assets","monsters")[quarry_handle]
KeyError: 'null'
```

```
  current_settlement -> 5877eb3c8740d970544368d2
  current_asset -> 5877eb3c8740d970544368d2
  current_view -> view_settlement
  created_on -> 2017-01-12 20:45:25.979000
  user_agent -> {u'is_mobile': False, u'browser': [u'Safari', [10, 0, 1], u'10.0.1']}
  login -> mdbarnett@gmail.com
  _id -> 5877eae58740d9700849e47e
```

My guess is that the quarry controls got a bad value from models.settlements.get_quarry_options() or one of those API methods and threw the legacy app a curve ball. 

Either way, it needs to be investigated and resolved.

**Comment by toconnell** [comment]
Alright, I cloned the user and replicated this. Looks like adding the Great Golden Cat is what does it:

![ggc_breaks_quarries](https://cloud.githubusercontent.com/assets/48043/21933316/8653eaaa-d96a-11e6-97b6-4e6c6184b184.PNG)

**Comment by toconnell** [comment]
Alright, so the acute cause here is that the JS app is sending "null" quarry handles to the legacy app, which then barfs, killing the session (because "null" is not a known monster handle, etc.).

The patch for now is to update kdmManager.js to throw an error and give up when it gets a null key.

This will go out in the next release.
