### ISSUE TITLE
Render failures re: custom AI look-ups

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#213]
From email:

```
[57979423421aa919d18016e0] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-01-16 17:43:40.210160.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 572, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 2641, in modify
 self.add_custom_AI(params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1508, in add_custom_AI
 ai_desc = params["custom_AI_desc"].value
File "/usr/lib/python2.7/cgi.py", line 540, in __getitem__
 raise KeyError, key
KeyError: 'custom_AI_desc'
```

```
 The session object was this:
  current_settlement -> 586983c68740d9200ec08fbd
  current_asset -> 586997e08740d936018b63ab
  access_token -> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6IjU3OTc5NDIzNDIxYWE5MTlkMTgwMTZlMCIsImlhdCI6MTQ4NDM1MzkxMCwibmJmIjoxNDg0MzUzOTEwLCJleHAiOjE0ODQzNTQyMTB9.zgRoZYRLO__Go0XFojiVDkloW8_LbeujPxeHnN103uU
  current_view -> view_survivor
  created_by -> 57979423421aa919d18016e0
  created_on -> 2017-01-14 00:31:50.840000
  user_agent -> {u'is_mobile': False, u'browser': [u'Chrome', [55, 0, 2883], u'55.0.2883']}
  login -> aspot22@gmail.com
  _id -> 587971768740d92d0163b940
```

Investigate and resolve.

**Comment by toconnell** [comment]
Looks like you can create these things without any description and we don't have graceful failures if the user sticks his hand into the Cuisinart.

**Comment by toconnell** [comment]
Alright, I added some HTML5 form validation (i.e. added 'required' to the input element) and then updated the function so that it bails and returns False if it hasn't got the full req.
