### ISSUE TITLE
Bow Mastery is causing render failures

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#218]
On this user's settlement: 5690062b421aa945d6abdb18

TB goes:
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 35, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 695, in current_view_html
 output += self.Settlement.render_html_summary(user_id=self.User.user["_id"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 56, in wrapper
 view_html = Template(render_func(self, *args, **kwargs))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5770, in render_html_summary
 endeavors = self.get_endeavors("html"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 4364, in get_endeavors
 sources = copy(self.get_game_asset("innovations", update_mins=False, handles_to_names=True))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5509, in get_game_asset
 name_list.append(lookup_dict[a_name]["name"])
KeyError: u'Mastery - Bow'
```

**Comment by toconnell** [comment]
Looks like we've got two problems:

- [ ] Adding a mastery to a survivor adds the mastery name (not handle) to settlement innovations (dang)
- [ ] Once a name is in there, it doesn't get normalized to a handle (we'll add that to enforce_data_model)

**Comment by toconnell** [comment]
Added a bug_fixes method that handles names in the innovations list and swaps them out for handles.

**Comment by toconnell** [comment]
Alright, the fix for this and the fix for affected settlements goes out in the next release.
