### ISSUE TITLE
Research and resolve "iron" issue causing tracebacks in production.

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#223]
From automatic render failure emails:

```
 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 35, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 705, in current_view_html
 output += self.render_user_asset_sheet("settlements")
File "/home/toconnell/kdm-manager/v1/session.py", line 614, in render_user_asset_sheet
 output = S.render_html_form()
File "/home/toconnell/kdm-manager/v1/assets.py", line 56, in wrapper
 view_html = Template(render_func(self, *args, **kwargs))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5806, in render_html_form
 storage = self.get_storage("html_buttons"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 4210, in get_storage
 resource_pool[resource_key] += 1
KeyError: 'iron'
```

Settlement ID: 5885ccf68740d918beba32ad
User ID: 58859cd68740d901a36c1c8b

**Comment by toconnell** [comment]
Looks like this was an issue with a couple of items having resource "family" attributes they should not have had. I fixed them and the next release will include the fix.
