### ISSUE TITLE
2.5.293 cleanup list

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#230]
- [x] World panel: fix settlement handles in campaign popularity contest
- [x] World panel: fix settlement handles in latest settlement
- [x] add 'special' options to /new_settlement output (GET)
- [ ] Investigate 'bloodline' traceback:
```
==> v2/api/log/api.log <==
[2017-03-20 22:14:23] DEBUG:    Migrated settlements object 'Palanthas' [58c988128740d94890532b7a] campaign attrib from 'People of the Stars' to 'people_of_the_stars'.
[2017-03-20 22:14:23] INFO:     settlements object 'Palanthas' [58c988128740d94890532b7a] settlement modified! Saving changes...
[2017-03-20 22:14:23] INFO:     Saved settlements object 'Palanthas' [58c988128740d94890532b7a] to mdb.settlements successfully!
[2017-03-20 22:14:25] ERROR:    Could not initialize innovation asset from dict: bloodline
[2017-03-20 22:14:25] ERROR:    Unable to add 'bloodline' to settlements object 'Palanthas' [58c988128740d94890532b7a] innovations!
[2017-03-20 22:14:25] ERROR:    Bad params were: {u'handle': u'bloodline'}
```
- [x] DO NOT serialize the whole user object in the auth token (slim it way down, in fact)
- [x] add the privacy/data usage stanza to the About panel
- [x] fix the API's "always_available" bug where lists are repetitive in /settlement/get/oid results
- [x] investivate the 'radiant_orb' traceback:
```
[5684b198421aa9675d795cfb] was logged out of the webapp instance on mona due to a render failure at 2017-03-24 12:56:29.640503.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 37, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 756, in current_view_html
 output += self.Settlement.render_html_summary(user_id=self.User.user["_id"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 56, in wrapper
 view_html = Template(render_func(self, *args, **kwargs))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5711, in render_html_summary
 endeavors = self.get_endeavors("html"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 4289, in get_endeavors
 sources = copy(self.get_game_asset("innovations", update_mins=False, handles_to_names=True))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5451, in get_game_asset
 name_list.append(lookup_dict[a_name]["name"])
KeyError: u'radiating_orb'
```
- [x] add a graceful failure for bad remove operations in the legacy app:
```
 [578ac58f421aa944e6f88748] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-03-18 03:42:41.803700.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 61, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 590, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 2665, in modify
 self.survivor["disorders"].remove(params[p].value)
ValueError: list.remove(x): x not in list
```

**Comment by toconnell** [comment]
Nailed down the "World" panel stuff. I'll dig into the API fixes tomorrow.

**Comment by toconnell** [comment]
The "radiating_orb" error was fixed previously (actually, it was identified as user error, because the user removed the expansion from the settlement, which is no longer possible in the legacy app, etc.)
