### ISSUE TITLE
Legacy webapp calls deprecated get_endeavor_tokens() func

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#243]
From email:

```
 [595551578740d974dd0a9317] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-06-29 19:35:49.772352.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 63, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 648, in process_params
 S.return_departing_survivors(self.params["return_departing_survivors"].value)
File "/home/toconnell/kdm-manager/v1/assets.py", line 4702, in return_departing_survivors
 if self.get_endeavor_tokens() == 0:
AttributeError: Settlement instance has no attribute 'get_endeavor_tokens'
```

**Comment by toconnell** [comment]
Fixing this by pulling the deprecated function call and just modifying the self.settlement["endeavor_tokens"] attrib directly, since it's officially part of the data model as of 2.11.259.

**Comment by toconnell** [comment]
This is fixed and going out tomorrow.
