### ISSUE TITLE
Can't add Endeavor Tokens

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#247]
I have yet another problem: it's impossible to add endeavor tokens at the campaign summary page. An error occurs every time:

![image](https://user-images.githubusercontent.com/21055254/27798758-2ad99c64-601b-11e7-870b-65efcfe5f8a1.png)

**Comment by toconnell** [comment]
Confirmed/reproduced. 

This is a typing problem (i.e. we're not duck-typing hard enough) in the new API methods for managing Endeavor tokens.

From the API log:

```
192.168.0.166 - - [03/Jul/2017 12:09:35] "POST /settlement/update_endeavor_tokens/58697dbb8740d9110e22cfd5 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toconnell/kdm-manager/v2/api/utils.py", line 232, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/toconnell/kdm-manager/v2/api/api.py", line 195, in collection_action
    return asset_object.request_response(action)
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1970, in request_response
    self.update_endeavor_tokens()
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 743, in update_endeavor_tokens
    new_val = self.settlement["endeavor_tokens"] + int(modifier)
TypeError: coercing to Unicode: need string or buffer, int found
```

**Comment by toconnell** [comment]
@eugene-shuvaev Alright, I've been able to reproduce this one and fix it: the problem was a data-typing issue that got introduced two releases back.

Thanks again for writing in!
