### ISSUE TITLE
API Bug: survivor weapon masteries

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#249]
Causing log-outs:

```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 63, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 641, in process_params
 self.set_current_settlement(s["settlement"], update_mins)
File "/home/toconnell/kdm-manager/v1/session.py", line 306, in set_current_settlement
 self.set_api_assets()
File "/home/toconnell/kdm-manager/v1/session.py", line 347, in set_api_assets
 Session=self,
File "", line 2, in route_to_dict
File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 74, in retry_decorator
 logger)
File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 33, in __retry_internal
 return f()
File "/home/toconnell/kdm-manager/v1/api.py", line 164, in route_to_dict
 raise Exception("API Failure!")
Exception: API Failure!
```

Affected user: 57b79eed421aa927c4899433

**Comment by toconnell** [comment]
Confirmed/reproduced:

```
192.168.0.110 - - [04/Jul/2017 14:27:07] "GET /settlement/get/5936b8f68740d93144183376 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toconnell/kdm-manager/v2/api/utils.py", line 232, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/toconnell/kdm-manager/v2/api/api.py", line 195, in collection_action
    return asset_object.request_response(action)
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 2103, in request_response
    return self.return_json()
  File "/home/toconnell/kdm-manager/v2/api/Models.py", line 459, in return_json
    return Response(response=self.serialize(), status=200, mimetype="application/json")
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 256, in serialize
    output["user_assets"].update({"survivor_weapon_masteries": self.get_survivor_weapon_masteries()})
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1361, in get_survivor_weapon_masteries
    survivor_weapon_masteries.add(ai)
TypeError: unhashable type: 'dict'
```

**Comment by toconnell** [comment]
This is the error:

```
            for ai in S.list_assets("abilities_and_impairments"):
                if ai["handle"] in WM.get_handles():
                    survivor_weapon_masteries.add(ai)
```

We're adding the dict instead of the handle.

**Comment by toconnell** [comment]
Fixing this and deploying a monkey patch:

```
1359             for ai in S.list_assets("abilities_and_impairments"):
1360                 if ai["handle"] in WM.get_handles():
1361                     survivor_weapon_masteries.add(ai["handle"])
```
