### ISSUE TITLE
Survivor Sheet: adding Fighting Arts w/ epithets throws a traceback

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#270]
From email:

> [598ff7b68740d90314dc0217] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-08-14 10:33:34.125946.
```
 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 63, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 678, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1813, in modify
 self.add_game_asset("fighting_art", game_asset_key)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1103, in add_game_asset
 self.update_epithets(epithet=asset_dict["epithet"])
AttributeError: Survivor instance has no attribute 'update_epithets'
```

**Comment by toconnell** [comment]
Commenting this out for now; Fighting Arts management is about to move to the API (in September, probably).
