### ISSUE TITLE
Legacy Webapp - 'models.py' raises exceptions while listing assets

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#273]
From email:

>  [57aa6ab9421aa94a7cfb040d] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-08-26 07:51:20.693102.

> The traceback from the exception was this:
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 63, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 678, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1813, in modify
 self.add_game_asset("fighting_art", game_asset_key)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1097, in add_game_asset
 fa_deck = FightingArts.build_survivor_deck(self, self.Settlement)
File "/home/toconnell/kdm-manager/v1/models.py", line 310, in build_survivor_deck
 fa_deck.extend(self.get_always_available(Settlement))
File "/home/toconnell/kdm-manager/v1/models.py", line 88, in get_always_available
 e_dict = game_assets.expansions[e]
KeyError: u'White Box & Promo'
```

This will go away when FA's and Disorders move to the API (which will happen very soon), but for now, this needs a band-aid.

**Comment by toconnell** [comment]
This is dirty, but it should hold for a week or so:

```
diff --git a/v1/models.py b/v1/models.py
index 5203547..51494c1 100644
--- a/v1/models.py
+++ b/v1/models.py
@@ -85,9 +85,10 @@ class Model:

             # then check the expansions
             for e in expansions:
-                e_dict = game_assets.expansions[e]
-                if "always_available" in e_dict.keys() and game_asset in e_dict["always_available"]:
-                    always_available.add(game_asset)
+                e_dict = game_assets.expansions.get(e, None)
+                if e_dict is not None:
+                    if "always_available" in e_dict.keys() and game_asset in e_dict["always_available"]:
+                        always_available.add(game_asset)

             # finally, check the asset itself
             asset_dict = self.get_asset(game_asset)
```

I'm going to monkey patch it in, and it'll go out in the World panel re-dux.
