### ISSUE TITLE
API: timeline update issue

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#277]
Saw this in the logs during the last deploy:

```
[2017-09-09 10:19:34] ERROR:    Could not create settlement event log message for settlements object 'Terra' [59b395f28740d9740fe63263]
[2017-09-09 10:19:34] ERROR:    'name'
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 875, in rm_timeline_event
    self.log_event("Automatically removed '%s' from Lantern Year %s" % (e["name"], e["ly"]))
KeyError: 'name'
```

**Comment by toconnell** [comment]
Yeah, gotta fix this. Just saw another one:

```
[2017-11-02 19:02:55] ERROR:    Could not create settlement event log message for settlements object 'Hiroshima' [59e3835a8740d93dab8f82d2]
[2017-11-02 19:02:55] ERROR:    'name'
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1070, in rm_timeline_event
    self.log_event("Automatically removed '%s' from Lantern Year %s" % (e["name"], e["ly"]))
KeyError: 'name'
```

**Comment by toconnell** [comment]
This may have been inadvertently resolved in the update to semantic logging.

This stanza addresses this issue (i.e. by preventing it from happening) and is probably the accidental fix:
```
1458         for e_dict in target_ly[e['sub_type']]:
1459             if e_dict.get(rm_attrib, None) == e[rm_attrib]:
1460                 target_ly[e['sub_type']].remove(e_dict)
1461                 self.log_event(
1462                     action='rm',
1463                     key="timeline (LY %s)" % t_index,
1464                     value=e["name"],
1465                     event_type="sysadmin"
1466                 )
1467                 success = True
```
