### ISSUE TITLE
Un-converted/migrated expansions break the dashboard loader

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#295]
Like so:

![dash](https://user-images.githubusercontent.com/48043/31284397-03b95874-aa7e-11e7-976c-b8ddcc2c9ac7.PNG)

**Comment by toconnell** [comment]
This is a _get_asset()_ fail:

```
[2017-10-06 10:37:13] ERROR:    The handle 'Gorm' is not in ['beta_challenge_scenarios', 'dragon_king', 'dung_beetle_
knight', 'flower_knight', 'gorm', 'green_knight_armor', 'lion_god', 'lion_knight', 'lonely_tree', 'manhunter', 'slend
erman', 'spidicules', 'sunstalker', 'white_box'] and could not be retrieved!
[2017-10-06 10:37:13] ERROR:    Could not serialize {u'quarries': [u'White Lion', u'Gorm', u'Screaming Antelope'], u'
campaign': u'People of the Lantern', u'locations': [u'Skinnery', u'Gormchymist', u'Bone Smith', u'Organ Grinder', u'G
ormery', u'Lantern Hoard'], u'innovations': [u'Symposium', u'Nigredo', u'Ammonia', u'Language', u'Lantern Oven'], u'c
reated_on': datetime.datetime(2016, 4, 5, 13, 50, 31, 716000), u'operation': u'increment', u'kill_board': {u'ly_4': [
u'Butcher Lvl 1'], u'ly_5': [u'Gorm Lvl 1'], u'ly_0': [u'White Lion (First Story)'], u'ly_1': [u'Gorm Lvl 1'], u'ly_2
': [u'Gorm Lvl 1'], u'ly_3': [u'Gorm Lvl 1']}, u'defeated_monsters': [u'White Lion (First Story)', u'Gorm Lvl 1', u'G
orm Lvl 1', u'Gorm Lvl 1', u'Butcher Lvl 1', u'Gorm Lvl 1'], u'storage': [u'Cloth', u'Cloth', u'Cloth', u'Cloth', u'B
one Axe', u'Bone Axe', u'Rawhide Boots', u'Rawhide Gloves', u'Rawhide Headband', u'Rawhide Vest', u'Gorment Mask', u'
Rib Blade', u'Armor Spikes', u'Monster Grease', u'Greater Gaxe', u'Skull Helm', u'Monster Grease', u'Monster Grease',
 u'Gaxe', u'Scrap', u'Scrap', u'Acid Tooth Dagger', u'Broken Lantern', u'Monster Organ', u'Skull'], u'created_by': Ob
jectId('565f3d67421aa95c4af1e230'), u'population': 0, u'current_quarry': None, u'lost_settlements': 0, u'timeline': [
{u'quarry_event': [u'White Lion (First Story)'], u'settlement_event': [u'First Day'], u'year': 0}, {u'quarry_event':
[u'Gorm Lvl 1'], u'settlement_event': [u'Acid Storm'], u'story_event': [u'Returning Survivors', u'The Approaching Sto
rm'], u'year': 1}, {u'quarry_event': [u'Gorm Lvl 1'], u'settlement_event': [u'Gorm Climate', u'Open Maw'], u'story_ev
ent': u'Endless Screams', u'year': 2}, {u'quarry_event': [u'Gorm Lvl 1'], u'settlement_event': [u'Gorm Climate', u'He
at Wave'], u'year': 3}, {u'quarry_event': [], u'nemesis_encounter': u'Nemesis Encounter: Butcher', u'settlement_event
': [u'Gorm Climate', u'Rivalry'], u'year': 4}, {u'quarry_event': [u'Gorm Lvl 1'], u'settlement_event': [u'Dark Dentis
t', u'Gorm Climate', u'Rivalry'], u'story_event': u'Hands of Heat', u'year': 5}, {u'story_event': [u'Armored Stranger
s', u'Game Over', u'Hooded Knight', u'Principle: Death', u'Principle: New Life', u'Principle: Society'], u'year': 6},
 {u'story_event': u'Phoenix Feather', u'year': 7}, {u'year': 8}, {u'nemesis_encounter': u"Nemesis Encounter: King's M
an", u'year': 9}, {u'year': 10}, {u'story_event': u'Regal Visit', u'year': 11}, {u'story_event': u'Principle: Convict
ion (p. 141)', u'year': 12}, {u'year': 13}, {u'year': 14}, {u'year': 15}, {u'nemesis_encounter': u'Nemesis Encounter'
, u'year': 16}, {u'year': 17}, {u'year': 18}, {u'nemesis_encounter': u'Nemesis Encounter', u'year': 19}, {u'story_eve
nt': u'Watched', u'year': 20}, {u'year': 21}, {u'year': 22}, {u'nemesis_encounter': u'Nemesis Encounter: Level 3', u'
year': 23}, {u'year': 24}, {u'year': 25}, {u'nemesis_encounter': u'Nemesis Encounter: Watcher', u'year': 26}, {u'year
': 27}, {u'year': 28}, {u'year': 29}, {u'year': 30}, {u'year': 31}, {u'year': 32}, {u'year': 33}, {u'year': 34}, {u'y
ear': 35}, {u'year': 36}, {u'year': 37}, {u'year': 38}, {u'year': 39}, {u'year': 40}], u'principles': [u'Survival of
the Fittest', u'Cannibalize'], u'nemesis_monsters': {u"King's Man": [], u'Butcher': [u'Lvl 1']}, u'abandoned': dateti
me.datetime(2016, 4, 11, 0, 4, 0, 305000), u'name': u'Gormora', u'milestone_story_events': [u'First time death count
is updated', u'First child is born', u'Population reaches 15'], u'lantern_year': 6, u'expansions': [u'Gorm'], u'death
_count': 14, u'_id': ObjectId('5703fae7421aa9653289bdb4'), u'survival_limit': 6}
[2017-10-06 10:37:13] ERROR:
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 555, in get_settlements
    sheet = json.loads(S.serialize('dashboard'))
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 315, in serialize
    output["sheet"].update({"expansions_pretty": self.get_expansions(str)})
  File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1378, in get_expansions
    output.append(E.get_asset(e)["name"])
  File "/home/toconnell/kdm-manager/v2/api/Models.py", line 186, in get_asset
    raise utils.InvalidUsage(msg)
InvalidUsage
```

**Comment by toconnell** [comment]
This is resolved. I updated a couple of the base class methods in _Models.py_ to have special back-offs for the White Box/Promo expansion and enhanced the Settlement object's _get_expansions()_ method to back off to names.

Monkey-patching this out to prod right now. Fortunately, it literally hit no production users (other than me).
