### ISSUE TITLE
Dashboard initialization failure

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#302]
From email:

> On a slightly related note, I reported also an issue, where shared members of the campaign cannot fetch campaign details. I asked for my friend login credentials, and the issue is same for me on my computer.

This looks like its barfing on the User's _get_friends()_ method, which continues to _not_ fail very gracefully.

**Comment by toconnell** [comment]
Confirmed:

```
192.168.0.153 - - [09/Oct/2017 09:03:33] "GET /user/dashboard/59ca71f08740d90655610498 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toconnell/kdm-manager/v2/api/utils.py", line 426, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/toconnell/kdm-manager/v2/api/api.py", line 203, in collection_action
    return asset_object.request_response(action)
  File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 615, in request_response
    return Response(response=self.serialize('dashboard'), status=200, mimetype="application/json")
  File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 284, in serialize
    output["user_facts"]["friend_count"] = self.get_friends(return_type=int)
  File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 467, in get_friends
    friend_ids.remove(self.user["_id"])
KeyError: ObjectId('59ca71f08740d90655610498')
```

**Comment by toconnell** [comment]
Looks like I was right: _get_friends()_ shits the bed when it tries to remove the user's ID from the list of IDs and it's not there.

The reason it's not there is a logic issue, where I am assuming that the user has created a survivor in at least one of the campaigns they're playing.

At any rate, this is fixed by making the removal of the user's own OID from the friends list conditional:

```
diff --git a/v2/api/models/users.py b/v2/api/models/users.py
index 228e4d8..d5b2c96 100644
--- a/v2/api/models/users.py
+++ b/v2/api/models/users.py
@@ -464,7 +464,8 @@ class User(Models.UserAsset):
                     friend_emails.add(survivor["email"])

             # you can't be friends with yourself
-            friend_ids.remove(self.user["_id"])
+            if self.user["_id"] in friend_ids:
+                friend_ids.remove(self.user["_id"])
             if self.user["login"] in friend_emails:
                 friend_emails.remove(self.user["login"])
```

Fix will go out in this week's release.
