### ISSUE TITLE
/admin/get/settlement_data throws an exception b/c of bad InvalidUsage() call

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#305]
Observe:

```
192.168.0.153 - - [12/Oct/2017 09:09:28] "GET /admin/get/settlement_data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12.2-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toconnell/kdm-manager/v2/api/api.py", line 233, in admin_view
    return request_broker.get_admin_data(resource)
  File "/home/toconnell/kdm-manager/v2/api/request_broker.py", line 65, in get_admin_data
    raise InvalidUsage(e, status_code=500)
NameError: global name 'InvalidUsage' is not defined
```

Investigate and resolve.

**Comment by toconnell** [comment]
This was...just a dumb mistake. This will be fixed in the next release:

```
diff --git a/v2/api/request_broker.py b/v2/api/request_broker.py
index 7b99cef..af74a41 100644
--- a/v2/api/request_broker.py
+++ b/v2/api/request_broker.py
@@ -62,7 +62,7 @@ def get_admin_data(resource=None):
     except Exception as e:
         logger.error("Unable to return '%s' admin data!" % resource)
         logger.error(e)
-        raise InvalidUsage(e, status_code=500)
+        raise utils.InvalidUsage(e, status_code=500)

     return utils.http_500
```
