### ISSUE TITLE
World: principle_selection_rates throws an exception

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#319]
```
[2017-10-18 20:08:22] ERROR:    Exception caught while refreshing 'principle_selection_rates' asset!
[2017-10-18 20:08:22] ERROR:
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 118, in refresh_asset
    self.update_asset_dict(asset_dict)
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 160, in update_asset_dict
    exec "value = self.%s()" % asset_dict["handle"]
  File "<string>", line 1, in <module>
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 764, in principle_selection_rates
    mep_dict = I.get_mutually_exclusive_principles()
  File "/home/toconnell/kdm-manager/v2/api/models/innovations.py", line 47, in get_mutually_exclusive_principles
    alternatives_list = [self.get_asset(option)["name"], self.get_asset(option)["handle"]]
  File "/home/toconnell/kdm-manager/v2/api/Models.py", line 186, in get_asset
    raise utils.InvalidUsage(msg)
InvalidUsage
```

The world.py log throws this:

```
[2017-10-19 20:37:27] DEBUG:    Refreshing 'principle_selection_rates' asset...
[2017-10-19 20:37:27] ERROR:    The handle 'survival_of_the_fittest' is not in ['albedo', 'ammonia', 'aquarobics', 'arena', 'bed', 'black_mask', 'bloodletting', 'bloodline', 'choreia
', 'citrinitas', 'clan_of_death', 'cooking', 'crimson_candy', 'dark_water_research', 'dragon_speech', 'drums', 'empire', 'face_painting', 'family', 'filleting_table', 'final_fighting
_art', 'forbidden_dance', 'guidepost', 'hands_of_the_sun', 'heart_flute', 'hovel', 'inner_lantern', 'language', 'lantern_oven', 'legless_ball', 'mastery_axe', 'mastery_bow', 'mastery
_club', 'mastery_dagger', 'mastery_fist_and_tooth', 'mastery_grand_weapon', 'mastery_katana', 'mastery_katar', 'mastery_scythe', 'mastery_shield', 'mastery_spear', 'mastery_sword', '
mastery_twilight_sword', 'mastery_whip', 'memento_mori', 'nightmare_training', 'nigredo', 'paint', 'partnership', 'petal_spiral', 'pictograph', 'pottery', 'radiating_orb', 'records',
 'round_stone_training', 'rubedo', 'sacrifice', 'saga', 'sauna_shrine', 'scarification', 'scrap_smelting', 'sculpture', 'settlement_watch', 'shadow_dancing', 'shrine', 'silk_refining
', 'song_of_the_brave', 'stoic_statue', 'storytelling', 'subterranean_agriculture', 'sun_language', 'symposium', 'the_knowledge_worm', 'ultimate_weapon', 'umbilical_bank', 'war_room'
, 'white_mask'] and could not be retrieved! 
```

**Comment by toconnell** [comment]
Looks like the problem is here:

```
 763     def principle_selection_rates(self):
 764         """ This is pretty much a direct port from V1. It's still a hot mess.
 765         This should probably get a refactor prior to launch. """
 766
 767         I = innovations_models.Assets()
 768         mep_dict = I.get_mutually_exclusive_principles()
```

For some reason, that AssetCollection object is being initialized without principles...

**Comment by toconnell** [comment]
argh.

Looks like I'm gonna be paying down some technical debt in this one...

**Comment by toconnell** [comment]
ok, I think this is resolved, but we won't know for sure until its deployed tonight. Closing this for now, however, because if it's still broken, it'll be something else that misfires when the daemon runs.
