### ISSUE TITLE
Legacy Webapp: endeavors look-up failure (potentially an expansion content problem)

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#340]
From email: 

```
 [5814af518740d9656bd51bbb] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-10-21 16:52:36.669033.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 38, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 755, in current_view_html
 output += self.Settlement.render_html_summary(user_id=self.User.user["_id"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 55, in wrapper
 view_html = Template(render_func(self, *args, **kwargs))
File "/home/toconnell/kdm-manager/v1/assets.py", line 2679, in render_html_summary
 endeavors = self.get_endeavors("html"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 1828, in get_endeavors
 innovation_names_list = copy(self.get_game_asset("innovations", update_mins=False, handles_to_names=True))
File "/home/toconnell/kdm-manager/v1/assets.py", line 2501, in get_game_asset
 name_list.append(lookup_dict[a_name]["name"])
KeyError: u'dark_water_research'
```

**Comment by toconnell** [comment]
This will go away when Endeavors migrate to the API (which will happen in the 1.5 release).

I'm moving this to that project/milestone and I'll close it out when I deprecate the method from the legacy app.

**Comment by toconnell** [comment]
This is fixed now that https://github.com/toconnell/kdm-manager/issues/355 has been resolved. Closing.
