### ISSUE TITLE
World: query for 'latest_fatality' throws a weird exception in prod

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#366]
```
[2017-10-27 20:09:45] ERROR:    Exception caught while refreshing 'latest_fatality' asset!
[2017-10-27 20:09:45] ERROR:    Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 118, in refresh_asset
    self.update_asset_dict(asset_dict)
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 160, in update_asset_dict
    exec "value = self.%s()" % asset_dict["handle"]
  File "<string>", line 1, in <module>
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 669, in latest_fatality
    return self.pretty_survivor(s)
  File "/home/toconnell/kdm-manager/v2/api/world.py", line 285, in pretty_survivor
    S = survivors_models.Survivor(_id=survivor["_id"])
  File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 97, in __init__
    if request.collection != 'survivor':
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

**Comment by toconnell** [comment]
Oh yeah. Assuming a request context on initializing a survivor. D'oh!

**Comment by toconnell** [comment]
Got it. 

This helped: https://stackoverflow.com/questions/40284800/check-if-flask-request-context-is-available
