### ISSUE TITLE
Settlement: new settlement creation failure in production

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#369]
This is...unsettling:

```
 [59f38f508740d97c487ca5a0] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-10-27 20:18:35.372429.

 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 567, in process_params
 raise RuntimeError(msg)
RuntimeError: An API error caused settlement creation to fail! API response was: 500 - Internal Server Error
```

**Comment by toconnell** [comment]
It's also recurring:

```
[2017-10-27 20:54:45] ERROR:    Caught exception while processing parameters for REDACTED (59f39cda8740d978cf8c835b)!
[2017-10-27 20:54:45] ERROR:    An API error caused settlement creation to fail! API response was: 500 - Internal Server Error
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
    return func(self, *args, **kwargs)
  File "/home/toconnell/kdm-manager/v1/session.py", line 567, in process_params
    raise RuntimeError(msg)
```

**Comment by toconnell** [comment]
OK, got it. This was a problem with incoming names from the form and it's fixed and pushed out.
