### ISSUE TITLE
Legacy: assets.py print debugging throws a traceback

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#389]
From email:

> [59f90b878740d9174c575970] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-11-01 00:00:57.596447.

> The traceback from the exception was this:
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 605, in process_params
 S.modify(self.params)
File "/home/toconnell/kdm-manager/v1/assets.py", line 1874, in modify
 self.logger.warn("%s -> %s (%s)" % (p, params[p], type(params[p])))
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by toconnell** [comment]
Fixed the problematic part (but leaving this in, until we completely shit-can all legacy webapp _modify()_ calls).
