### ISSUE TITLE
API: Survivor.rm_cursed_item() failure

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#394]
From email:

> [59fb6af98740d91ec4ebcb0e].

> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/survivor/rm_cursed_item/59fb6b9b8740d91ec4ebcb21
>JSON: {u'handle': u'twilight_sword'}
```
The full traceback is as follows:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 427, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 225, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 2742, in request_response
 self.rm_cursed_item()
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 556, in rm_cursed_item
 asset_class, ci_dict = self.get_asset('cursed_items', handle)
AttributeError: Survivor instance has no attribute 'get_asset'
```

The _get_asset()_ method was shit-canned a few releases back...I must have missed this method when I refactored.

**Comment by toconnell** [comment]
Looks like it's only still present in _rm_cursed_item()_, which is good.

**Comment by toconnell** [comment]
Done. ready to roll.
