### ISSUE TITLE
Legacy Webapp: traceback when rendering survivor __repr__

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#400]
From auto-email:

> [57aa6ab9421aa94a7cfb040d] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-11-08 19:00:16.204841.
```
 The traceback from the exception was this:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 429, in process_params
 S.remove()
File "/home/toconnell/kdm-manager/v1/assets.py", line 1019, in remove
 S.remove()
File "/home/toconnell/kdm-manager/v1/assets.py", line 410, in remove
 self.logger.info("[%s] removing survivor %s" % (self.User, self))
File "/home/toconnell/kdm-manager/v1/assets.py", line 265, in __repr__
 return self.get_name_and_id(include_id=False, include_sex=True)
File "/home/toconnell/kdm-manager/v1/assets.py", line 430, in get_name_and_id
 return " ".join(output)
TypeError: sequence item 0: expected string, list found
```

No idea why this is happening (or why now).

**Comment by toconnell** [comment]
I'm unable to replicate this by removing a random survivor in a test settlement. Gonna have to clone the user down.

**Comment by toconnell** [comment]
Found an unrelated bug where removed survivors were being retrieved by the API after removal.

**Comment by toconnell** [comment]
I just removed every survivor in this guy's settlment and was not able to reproduce. I really hope he emails me.

**Comment by toconnell** [comment]
It's been almost a week and no recurrence or user contact. Closing this one.
