### ISSUE TITLE
API: settlements created without 'nemesis_monsters' attribute

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#403]
Production Settlement OID: 59c50ef98740d9046bcab463

```
toconnell@ubuntu-trusty-1:~/kdm-manager/v1$ ./admin.py -c settlements -v 59c50ef98740d9046bcab463

 _id                            <class 'bson.objectid.ObjectId'>      |59c50ef98740d9046bcab463|
 admins                         <type 'list'>                         |[u'kaythxs@gmail.com']|
 campaign                       <type 'unicode'>                      |people_of_the_lantern|
 created_by                     <class 'bson.objectid.ObjectId'>      |57ee63138740d9717d8bb584|
 created_on                     <type 'datetime.datetime'>            |2017-09-22 13:24:09.154000|
 custom_epithets                <type 'list'>                         |[]|
 death_count                    <type 'int'>                          |0|
 defeated_monsters              <type 'list'>                         |[]|
 endeavor_tokens                <type 'int'>                          |0|
 expansions                     <type 'list'>                         |[]|
 innovation_levels              <type 'dict'>                         |{}|
 innovations                    <type 'list'>                         |[]|
 lantern_year                   <type 'int'>                          |0|
 location_levels                <type 'dict'>                         |{}|
 locations                      <type 'list'>                         |[]|
 lost_settlements               <type 'int'>                          |0|
 meta                           <type 'dict'>                         |{u'milestones_version': 1.0, u'monsters_version': 1.0, u'locations_version': 1.0, u'expansions_version': 1.0, u'innovations_version': 1.0, u'principles_version': 1.0, u'timeline_version': 1.1, u'campaign_version': 1.0, u'storage_version': 1.0}|
 milestone_story_events         <type 'list'>                         |[]|
 name                           <type 'unicode'>                      |Lux|
 population                     <type 'int'>                          |0|
 principles                     <type 'list'>                         |[]|
 storage                        <type 'list'>                         |[]|
 survival_limit                 <type 'int'>                          |1|
```

**Comment by toconnell** [comment]
Auto-alert email:

>  [57ee63138740d9717d8bb584].
>
>  The request details are as follows:
> Method: GET
> URL: http://api.thewatcher.io/settlement/get/59c50ef98740d9046bcab463
> JSON: None
>
> The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 433, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 226, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3345, in request_response
 return Response(response=self.serialize(), status=200, mimetype="application/json")
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 418, in serialize
 output["game_assets"]["nemesis_options"] = self.get_monster_options("nemesis_monsters")
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 2717, in get_monster_options
 for n in self.settlement[monster_type]:
KeyError: 'nemesis_monsters'
```

Now sure how this is possible. Gotta investigate.

**Comment by toconnell** [comment]
The _settlement_sheet_init_ dictionary for the PotLantern campaign asset is this:

```
        "settlement_sheet_init": {
            "quarries": ["white_lion"],
            "nemesis_monsters": ["butcher"],
            "nemesis_encounters": {'butcher': []}
        },
```

...and none of those keys are present, suggesting that this part of the _new()_ method didn't fire during creation:

```
        for init_key in self.campaign.settlement_sheet_init.keys():
            self.settlement[init_key] = copy(self.campaign.settlement_sheet_init[init_key])
        self.logger.info("%s initialized settlement sheet for '%s'" % (request.User, self))
```

**Comment by toconnell** [comment]
This was almost certainly a one-time thing and the result of a bug that's been fixed. Closing WF.
