### ISSUE TITLE
API: exception from /settlement/add_defeated_monster/<oid> 

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#406]
From email:

> [5a0abdcb8740d924cb5cec82].

> The request details are as follows:
> Method: POST
> URL: http://api.thewatcher.io/settlement/add_defeated_monster/5a0abe568740d92529a56bf2
> JSON: {u'monster': None}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 433, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 226, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3378, in request_response
 self.add_defeated_monster()
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 572, in add_defeated_monster
 M = monsters.Monster(name=monster_string)
File "/home/toconnell/kdm-manager/v2/api/models/monsters.py", line 55, in __init__
 self.initialize()
File "/home/toconnell/kdm-manager/v2/api/Models.py", line 357, in initialize
 elif handle is None and name is None:
NameError: global name 'handle' is not defined
```

**Comment by toconnell** [comment]
These are just missing the _self_ reference:

```
diff --git a/v2/api/Models.py b/v2/api/Models.py
index 4a3c500..7b937d5 100644
--- a/v2/api/Models.py
+++ b/v2/api/Models.py
@@ -356,7 +356,7 @@ class GameAsset(object):
             self.initialize_from_handle()
         elif self.name is not None:
             self.initialize_from_name()
-        elif handle is None and name is None:
+        elif self.handle is None and self.name is None:
             raise AssetInitError("Asset objects must be initialized with 'handle' or 'name' kwargs.")
         else:
             raise AssetInitError()
```
