### ISSUE TITLE
Survivors: set_many_attributes() throws exceptions

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#410]
Related to https://github.com/toconnell/kdm-manager/issues/405

From auto-alert emails:
>  [5a0b91b68740d934067b544d].
>
> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/survivor/set_many_attributes/5a0b94268740d934067b54d9
>JSON: `{u'attributes': [{u'attribute': u'Strength', u'value': 1}, {u'attribute': u'Movement', u'value': 5}, {u'attribute': u'Accuracy', u'value': 1}, {u'attribute': u'Evasion', u'value': 1}, {u'attribute': u'Luck', u'value': 0}, {u'attribute': u'Speed', u'value': 0}], u'user_id': u'5a0b91b68740d934067b544d', u'attribute_details': [{u'attribute': u'Strength', u'detail': u'token', u'value': 0}, {u'attribute': u'Movement', u'detail': u'token', u'value': 0}, {u'attribute': u'Accuracy', u'detail': u'token', u'value': 0}, {u'attribute': u'Evasion', u'detail': u'token', u'value': 0}, {u'attribute': u'Luck', u'detail': u'token', u'value': 0}, {u'attribute': u'Speed', u'detail': u'token', u'value': 0}, {u'attribute': u'Strength', u'detail': u'gear', u'value': 0}, {u'attribute': u'Movement', u'detail': u'gear', u'value': 0}, {u'attribute': u'Accuracy', u'detail': u'gear', u'value': 0}, {u'attribute': u'Evasion', u'detail': u'gear', u'value': 0}, {u'attribute': u'Luck', u'detail': u'gear', u'value': 0}, {u'attribute': u'Speed', u'detail': u'gear', u'value': 0}]}`

```
The full traceback is as follows:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 445, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 231, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 2814, in request_response
 self.set_many_attributes()
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 1495, in set_many_attributes
 self.set_attribute(attrib, detail, value, False)
TypeError: set_attribute() takes at most 4 arguments (5 given)
```

@calebkester This is the email I fwd'd you yesterday. I'll get it done in the break/fix release that I'm working on now.

**Comment by CalebKester** [comment]
Awesome thanks! was this due to the fact that I threw in the updated details before you released it or was this another bug?

**Comment by toconnell** [comment]
Alright, this is working in test now:

![set_many_attributes_success](https://user-images.githubusercontent.com/48043/32843330-1cc04086-c9e5-11e7-958b-60a3001d44cc.PNG)

event log output:

```
[2017-11-15 09:08:50] DEBUG:    [POST] http://192.168.0.110:8013/survivor/set_many_attributes/59ff9ed68740d9155a483ad1 response in 0:00:00.009270
[2017-11-15 09:09:29] DEBUG:    [GET] http://192.168.0.110:8013/admin/get/user_data response in 0:00:00.149212
[2017-11-15 09:09:30] DEBUG:    [GET] http://192.168.0.110:8013/admin/get/logs response in 0:00:00.747488
[2017-11-15 09:09:30] DEBUG:    [GET] http://192.168.0.110:8013/world response in 0:00:00.011861
[2017-11-15 09:09:38] WARNING:  'user_id' key in POST body; attempting Khoa-style token-less auth...
[2017-11-15 09:09:38] DEBUG:    settlements object 'Darill's Tomb' [59f7d7208740d92787bf2fd4] initialize() -> in 0:00:00.195513
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Strength' to 1
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Movement' to 5
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Accuracy' to 1
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Evasion' to 1
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Luck' to 0
[2017-11-15 09:09:38] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Speed' to 0
[2017-11-15 09:09:38] ERROR:    Survivor 'attribute_detail' detail type 'token' is not supported!
[2017-11-15 09:09:38] DEBUG:    [POST] http://192.168.0.110:8013/survivor/set_many_attributes/59ff9ed68740d9155a483ad1 response in 0:00:00.232654
[2017-11-15 09:10:29] DEBUG:    [GET] http://192.168.0.110:8013/admin/get/user_data response in 0:00:00.164582
[2017-11-15 09:10:30] DEBUG:    [GET] http://192.168.0.110:8013/admin/get/logs response in 0:00:00.747951
[2017-11-15 09:10:30] DEBUG:    [GET] http://192.168.0.110:8013/world response in 0:00:00.010042
[2017-11-15 09:11:21] WARNING:  'user_id' key in POST body; attempting Khoa-style token-less auth...
[2017-11-15 09:11:21] DEBUG:    settlements object 'Darill's Tomb' [59f7d7208740d92787bf2fd4] initialize() -> in 0:00:00.192266
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Strength' to 1
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Movement' to 5
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Accuracy' to 1
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Evasion' to 1
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Luck' to 0
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Speed' to 0
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Strength' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Movement' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Accuracy' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Evasion' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Luck' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Speed' detail 'tokens' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Strength' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Movement' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Accuracy' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Evasion' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Luck' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    Hector [M] (59ff9ed68740d9155a483ad1) event: toconnell@tyrannybelle.com set Hector [M] 'Speed' detail 'gear' to 0
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] INFO:     Saved Hector [M] (59ff9ed68740d9155a483ad1) to mdb.survivors successfully!
[2017-11-15 09:11:21] DEBUG:    [POST] http://192.168.0.110:8013/survivor/set_many_attributes/59ff9ed68740d9155a483ad1 response in 0:00:00.276635
```

@CalebKester @chibird12 Make sure you use 'tokens' as the `detail` (i.e. not 'token') when constructing the POST body for this one.

I'm going to get this fix included in today's break/fix release.

**Comment by toconnell** [comment]
Unblocks: https://github.com/Playing-Indoors/KDM_WWW/issues/76
