### ISSUE TITLE
Legacy Webapp: deprecate references to the new() method for Settlements

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#414]
From email:

>[5a0e151e8740d92a833528ae] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-11-16 22:58:07.274737.
>
> The traceback from the exception was this:
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 566, in process_params
 S = assets.Settlement(settlement_id=user_asset_id, session_object=self)
File "/home/toconnell/kdm-manager/v1/assets.py", line 931, in __init__
 settlement_id = self.new()
AttributeError: Settlement instance has no attribute 'new'
```

Honestly not even sure how this guy set this off.

**Comment by toconnell** [comment]
Removed this code. We should get a good, old-fashioned total render failure next time this happens.
