### ISSUE TITLE
Settlements: get_available_endeavors() is throwing some kind of exception

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#420]
From auto-email:

>  [56d96c98421aa93c5078abc7].
>
> The request details are as follows:
>Method: GET
>URL: http://api.thewatcher.io/settlement/get_campaign/5923e92e8740d931411dfbcc
>SON: None

>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 445, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 231, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3381, in request_response
 return Response(response=self.serialize('campaign'), status=200, mimetype="application/json")
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 463, in serialize
 output['campaign'].update({'endeavors': self.get_available_endeavors()})
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1814, in get_available_endeavors
 event_asset = self.Events.get_asset(event_dict['handle'])
KeyError: 'handle'
```

**Comment by toconnell** [comment]
Looks like we're processing events that only have names...which...why does that happen? That seems like it is the real bug here.

**Comment by toconnell** [comment]
OK--this now logs a warn and skips the offending event. We'll have to go through and look at the events and clean them up at some point...

**Comment by toconnell** [comment]
Fixed 'Gorm Climate' (i.e. `gorm_gorm_climate`).
