### ISSUE TITLE
Survivor Sheet: the add_cursed_item endpoint throws an exception on a POST w/ no JSON

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#428]
Missing request JSON causes this:

> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/survivor/add_cursed_item/59df87658740d93da2798b4c
> JSON: None
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 459, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 237, in collection_action
 request.User = users.token_to_object(request, strict=False)  # temporarily non-strict
File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 161, in token_to_object
 if request.method == "POST" and request.json.get('user_id', None) is not None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by toconnell** [comment]
This is fixed in https://github.com/toconnell/kdm-manager/issues/433

Closing.
