### ISSUE TITLE
Legacy webapp post fails b/c session has no settlement

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#429]
From email:

>  [5a1d3f338740d9723e644c29] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2017-11-28 10:51:47.578661.
>
> The traceback from the exception was this:
>Traceback (most recent call last):
```
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 573, in process_params
 POST_params = {"settlement": self.Settlement.settlement["_id"], "sex": letter, "public": True,}
AttributeError: 'NoneType' object has no attribute 'settlement'
```

**Comment by toconnell** [comment]
Looks like this happens during multiple survivor creation somehow...

**Comment by toconnell** [comment]
I think...it may be time to just cut this over to a pure API thing and completely obliterate the legacy webapp's middleman role in this.

**Comment by toconnell** [comment]
Closing this out (i.e. resolving it) because it is no longer possible to execute the code above (i.e. because it's deprecated).
