### ISSUE TITLE
Event Log: traceback from get_event_log on JSON-less POST

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#433]
From the auto-emailer:

> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/settlement/get_event_log/57ccc3008740d951a50eb43c
>JSON: None
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 459, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 237, in collection_action
 request.User = users.token_to_object(request, strict=False)  # temporarily non-strict
File "/home/toconnell/kdm-manager/v2/api/models/users.py", line 161, in token_to_object
 if request.method == "POST" and request.json.get('user_id', None) is not None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by toconnell** [comment]
This should fix it:
```
@@ -158,7 +158,7 @@ def token_to_object(request, strict=True):
     response OR a user object. Requires the application's initialized JWT to
     work. """
     # khoa's back door - chop this whole block when he gets CORS sorted out
-    if request.method == "POST" and request.json.get('user_id', None) is not None:
+    if request.method == "POST" and request.json is not None and request.json.get('user_id', None) is not None:
         logger.warn("'user_id' key in POST body; attempting Khoa-style token-less auth...")
         try:
             user_oid = ObjectId(request.json['user_id'])
```

**Comment by toconnell** [comment]
Closing this. It's going out in the next release.
