### ISSUE TITLE
 Controls of Death: incoming/raw user strings need to be duck punched down to unicode (damnit)

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#442]
From auto-alert emails:

> [5a0c8b508740d934067b66c9].

> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/survivor/controls_of_death/5a2a5c128740d948c6d73ec9
>JSON: {u'cause_of_death': u'Non \xe8 mai esistito', u'dead': True, u'died_in': 3}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 459, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 245, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 2919, in request_response
 self.controls_of_death()
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 1364, in controls_of_death
 self.survivor['cause_of_death'] = str(self.params["cause_of_death"])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 4: ordinal not in range(128)
```

**Comment by toconnell** [comment]
Wrapped this in a try/except and captured the error (so I can raise it back to the requester):

![ccod_fail](https://user-images.githubusercontent.com/48043/33845800-3bd840e2-de6a-11e7-82f7-c55ee1d78659.PNG)

**Comment by toconnell** [comment]
Alright: this is fixed:

```
@@ -1361,7 +1456,11 @@ class Survivor(Models.UserAsset):
                 self.survivor["died_in"] = self.Settlement.get_current_ly()

             if 'cause_of_death' in self.params:
-                self.survivor['cause_of_death'] = str(self.params["cause_of_death"])
+                try:
+                    self.survivor['cause_of_death'] = self.params["cause_of_death"].encode('ascii','ignore')
+                except Exception as e:
+                    self.logger.exception(e)
+                    raise utils.InvalidUsage("Could not set custom type of death! Exception was: %s" % e)
             else:
                 self.survivor['cause_of_death'] = "Unspecified"
```

It's brutal, but...at least we're logging the fact that we're abandoning characters.
