### ISSUE TITLE
API Utils: failure when returning survivors due to upper-ascii chars

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#450]
From auto-alert email:

> The request details are as follows:
> Method: POST
>URL: http://api.thewatcher.io/settlement/return_survivors/5a2f9bc58740d96dac136294
> JSON: {u'aftermath': u'victory'}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 459, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 254, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3564, in request_response
 self.return_survivors()
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1220, in return_survivors
 returners = utils.list_to_pretty_string(live_returns)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 178, in list_to_pretty_string
 l = [str(i) for i in l]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 2: ordinal not in range(128)
```

**Comment by toconnell** [comment]
Hammering it:
```
diff --git a/v2/api/utils.py b/v2/api/utils.py
index 599349c..aa2df8c 100755
--- a/v2/api/utils.py
+++ b/v2/api/utils.py
@@ -175,7 +175,7 @@ def list_to_pretty_string(l, quote_char=False):
     if quote_char:
         l = [str("%s%s%s" % (quote_char,i,quote_char)) for i in l]
     else:
-        l = [str(i) for i in l]
+        l = [i.encode('ascii','ignore') for i in l]

     return " and ".join([", ".join(l[:-1]), l[-1]])
```
:feelsgood:
