### ISSUE TITLE
Nginx: update the API webserver configs to handle big file uploads

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#451]
From the legacy webapp:

```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 512, in process_params
 raise RuntimeError(msg)
RuntimeError: An API error caused survivor creation to fail! API response was: 413 - Request Entity Too Large
```

**Comment by toconnell** [comment]
Updated:
```
diff --git a/v2/api/nginx/production b/v2/api/nginx/production
index 6b2c46b..5b251d7 100644
--- a/v2/api/nginx/production
+++ b/v2/api/nginx/production
@@ -27,6 +27,7 @@ server {
     error_log   /var/log/nginx/api.thewatcher.io_error.log;

     large_client_header_buffers 4 32k;
+    client_max_body_size 5M;    # big-ass avatar image support

     ### Locations
     location / {
```
