### ISSUE TITLE
Settlement: get_innovation_deck() error on 'graves' (asset handle)

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#454]
From auto-emails:

> [59ecfe088740d94630ddabc3].
> The request details are as follows:
>Method: GET
>URL: http://api.thewatcher.io/settlement/get_innovation_deck/59ecff428740d9473aea412c
>JSON: None
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 475, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 254, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3461, in request_response
 return Response(response=self.get_innovation_deck("JSON"), status=200, mimetype="application/json")
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 2168, in get_innovation_deck
 if available[i_handle].get("consequences",None) is not None:
KeyError: u'graves'
```

**Comment by toconnell** [comment]
This logs an error now and fails gracefully:

```
@@ -2165,7 +2163,9 @@ class Settlement(Models.UserAsset):
         # remove ones we've already got and make a list of consequences
         consequences = []
         for i_handle in self.settlement["innovations"]:
-            if available[i_handle].get("consequences",None) is not None:
+            if i_handle not in available.keys():
+                self.logger.error("%s Innovation handle '%s' is not a known innovation!" % (self, i_handle))
+            elif available[i_handle].get("consequences",None) is not None:
                 consequences.extend(available[i_handle]["consequences"])
             if i_handle in available.keys():
                 del available[i_handle]
```

**Comment by toconnell** [comment]
...and I wrote a bug fix:

```
@@ -3012,7 +3012,13 @@ class Settlement(Models.UserAsset):
     def bug_fixes(self):
         """ In which we burn CPU cycles to fix our mistakes. """

-        # 2017-10-05 legacy data bug
+        # 2017-12-16 - principles in the innovations list
+        for i in self.list_assets('innovations'):
+            if i.get('sub_type', None) == 'principle':
+                self.settlement['innovations'].remove(i['handle'])
+                self.logger.warn("%s Removed principle '%s' from innovations list!" % (self, i['name']))
+
```
