### ISSUE TITLE
Utils: pretty listing integers throws a traceback

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#455]
Looks like Thursday's fix introduced a new issue.

From auto-alert emails:

>[570ab8fb421aa9413a3aad66].

> The request details are as follows:
>Method: POST
>URL: http://api.thewatcher.io/settlement/update_nemesis_levels/5a1945e58740d974c3002539
>JSON: {u'levels': [1, 2, 3], u'handle': u'butcher'}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 475, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 254, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3487, in request_response
 self.update_nemesis_levels()
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1553, in update_nemesis_levels
 self.log_event('%s updated %s encounters to include %s' % (request.User.login, m_dict["name"], utils.list_to_pretty_string(levels)))
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 178, in list_to_pretty_string
 l = [i.encode('ascii','ignore') for i in l]
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by toconnell** [comment]
This is ugly, but I honestly don't have time for the 'correct' solution right now:

```
@@ -175,7 +175,10 @@ def list_to_pretty_string(l, quote_char=False):
     if quote_char:
         l = [str("%s%s%s" % (quote_char,i,quote_char)) for i in l]
     else:
-        l = [i.encode('ascii','ignore') for i in l]
+        try:
+            l = [i.encode('ascii','ignore') for i in l]
+        except:
+            l = [i for i in l]
```
