### ISSUE TITLE
Survivor Sheet - API error on /survivor/set_survival = None

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#458]
From auto-alert emails:

>Method: POST
>URL: http://api.thewatcher.io/survivor/set_survival/5a56091b8740d960d1159724
>JSON: {u'serialize_on_response': True, u'value': None}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 482, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
 return self._get_current_object()(*a, **kw)
File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
 return self.run(*args, **kwargs)
File "/home/toconnell/kdm-manager/v2/api/api.py", line 264, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 3244, in request_response
 self.set_survival()
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 2170, in set_survival
 value = int(self.params["value"])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by toconnell** [comment]
Also appears to be happening on /survivor/set_attribute/<oid> as well:


>Method: POST
>URL: http://api.thewatcher.io/survivor/set_attribute/5a3d525f8740d91e0708cc37
>JSON: {u'attribute': u'Insanity', u'value': None}

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 482, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 254, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 3131, in request_response
 self.set_attribute()
File "/home/toconnell/kdm-manager/v2/api/models/survivors.py", line 1660, in set_attribute
 value = int(self.params["value"])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by toconnell** [comment]
Forcing None type values to zero now:

```
diff --git a/v2/api/models/survivors.py b/v2/api/models/survivors.py
index 0963268..295572c 100644
--- a/v2/api/models/survivors.py
+++ b/v2/api/models/survivors.py
@@ -1728,6 +1728,8 @@ class Survivor(Models.UserAsset):
         if attrib is None:
             self.check_request_params(['attribute','value'])
             attrib = self.params["attribute"]
+            if value is None:
+                value = 0
             value = int(self.params["value"])

         # sanity check!
@@ -2167,6 +2169,8 @@ class Survivor(Models.UserAsset):
         about whether to enforce the Survival Limit. Will not go below zero. """

         self.check_request_params(["value"])
+        if value is None:
+            value = 0
         value = int(self.params["value"])
         self.survivor["survival"] = value
         self.apply_survival_limit()
```
