### ISSUE TITLE
api.py: legacy post_JSON_to_route() fails to transmit images to /new/survivor API call

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#461]
> [57994c5b421aa9482d63e48d] was logged out of the webapp instance on ubuntu-trusty-1 due to a render failure at 2018-01-15 20:17:54.217094.
>
> The traceback from the exception was this:
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 64, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 511, in process_params
 response = api.post_JSON_to_route("/new/survivor", payload=POST_params, Session=self)
File "", line 2, in post_JSON_to_route
File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 74, in retry_decorator
 logger)
File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 33, in __retry_internal
 return f()
File "/home/toconnell/kdm-manager/v1/api.py", line 143, in post_JSON_to_route
 raise Exception(e)
Exception: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte****
```

**Comment by toconnell** [comment]
Can't replicate this in dev, so it's got to be something browser-specific (or at least browser-related).

**Comment by toconnell** [comment]
Still can't replicate, so I'm re-enabling extreme failure exception logging in the method that POSTs the JSON to the API:

```
toconnell@mona:~/kdm-manager$ git diff v1/api.py
diff --git a/v1/api.py b/v1/api.py
index 4325479..4d13553 100755
--- a/v1/api.py
+++ b/v1/api.py
@@ -137,10 +137,9 @@ def post_JSON_to_route(route=None, payload={}, headers={}, Session=None):
         return requests.post(req_url, data=json.dumps(payload, cls=customJSONencoder), headers=h, verify=False)
     except Exception as e:
         msg = "api.post_JSON_to_Route() call failed! Exception caught while creating request object!"
-#        logger.error(msg)
-#        logger.exception(e)
-#        raise Exception("\n".join([msg, str(payload)]))
-        raise Exception(e)
+        logger.exception(e)
+        raise Exception("\n".join([msg, str(payload)]))
+#        raise Exception(e)
```

...leaving the ticket open, in the hopes of capturing this the next time it happens.

**Comment by toconnell** [comment]
Alright, this is popping up more and more: I got three alerts about it in the last three days.

I fished this traceback out of the _index.log_ from the legacy app:

```
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v1/api.py", line 137, in post_JSON_to_route
    return requests.post(req_url, data=json.dumps(payload, cls=customJSONencoder), headers=h, verify=False)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by toconnell** [comment]
I'm feeling more and more like the solution is just to shit-can legacy webapp survivor creation and resolve this one by finishing https://github.com/toconnell/kdm-manager/issues/462

**Comment by toconnell** [comment]
Closing this one out, as it is superseded by #462
