### ISSUE TITLE
Settlement Sheet: Innovation Deck throws error; fails to load

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#486]
From the production logs:

>Method: POST
>URL: http://api.thewatcher.io/settlement/get_innovation_deck/5a98ebc48740d95441eef857
>JSON: {u'return_type': u'dict', u'serialize_on_response': True}
>
>The full traceback is as follows:
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 505, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
 return self._get_current_object()(*a, **kw)
File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
 return self.run(*args, **kwargs)
File "/home/toconnell/kdm-manager/v2/api/api.py", line 274, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3765, in request_response
 return Response(response=self.get_innovation_deck(), status=200, mimetype="application/json")
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 2427, in get_innovation_deck
 deck_dict[i] = i_dict
NameError: global name 'i' is not defined
```

**Comment by toconnell** [comment]
Looks like it's the "last chance" method that looks for innovations such as "Settlement Watch" that show up in the deck for random/non-consequential reasons.

**Comment by toconnell** [comment]
...and it was just a couple of typos. Fix goes out today.
