### ISSUE TITLE
Campaign Summary: un-handled outcome when returning departing survivors

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#498]
> User OID: 5aa973618740d905cdc7e7ea
> Method: POST
> URL: http://api.thewatcher.io/settlement/return_survivors/5aaa5e8f8740d905cb812103
> JSON: {u'aftermath': u'defeat', u'serialize_on_response': True}
> 
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
 rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager/v2/api/utils.py", line 516, in wrapped_function
 resp = make_response(f(*args, **kwargs))
File "/home/toconnell/kdm-manager/v2/api/api.py", line 274, in collection_action
 return asset_object.request_response(action)
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 3995, in request_response
 self.return_survivors()
File "/home/toconnell/kdm-manager/v2/api/models/settlements.py", line 1387, in return_survivors
 self.log_event(msg, event_type="survivors_return_%s" % aftermath)
UnboundLocalError: local variable 'msg' referenced before assignment
```

**Comment by toconnell** [comment]
Turns out this is customer-facing:

![defeated_return_err](https://user-images.githubusercontent.com/48043/39131582-6d5e1438-46d5-11e8-8c5f-53b3528a9c6b.PNG)
