### ISSUE TITLE
Avatar averages (per user world.py calc) throw a gridfs error

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#53]
```
[2016-09-11 18:21:21] ERROR:    'GridFS' object has no attribute 'find'
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager/v1/session.py", line 397, in current_view_html
    output += self.User.html_world()
  File "/home/toconnell/kdm-manager/v1/assets.py", line 350, in html_world
    user_averages = world.user_average()
  File "/home/toconnell/kdm-manager/v1/world.py", line 296, in user_average
    avatar_count = gridfs.GridFS(mdb).find({"created_by": user["_id"]}).count()
AttributeError: 'GridFS' object has no attribute 'find'
```

**Comment by toconnell** [comment]
...which is fucked up, because it definitely doesn't happen in test.

**Comment by toconnell** [comment]
Looks like it could be a version thing:

http://stackoverflow.com/questions/29666420/attributeerror-gridfs-object-has-no-attribute-find

**Comment by toconnell** [comment]
Going to try to force the python binary and see if that fixes it...

**Comment by toconnell** [comment]
Nope. Looks like a package thing:

```
toconnell@ubuntu-trusty-1:~$ aptitude show python-gridfs
Package: python-gridfs            
State: installed
Automatically installed: no
Version: 2.6.3-1build1
Priority: optional
Section: python
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 92.2 k
Depends: python (>= 2.7), python (< 2.8), python:any (>= 2.7.1-0ubuntu2), python-pymongo
Provides: python2.7-gridfs
Description: Python implementation of GridFS for MongoDB
 GridFS is a storage specification for large objects in MongoDB. The Python gridfs module is an implementation based on the pymongo module. It provides
 a file-like interface.
Homepage: http://api.mongodb.org/python/
```

#shitSnacks

**Comment by toconnell** [comment]
Looks like we're going to have to rewrite...I'm not tampering with packages on this VM.

**Comment by toconnell** [comment]
Alright, this is done:

```
295 #       gridfs queries need version 2.7+ of the gridfs pymongo driver
296 #        avatar_count = gridfs.GridFS(mdb).find({"created_by": user["_id"]}).count()
297         avatar_count = mdb.survivors.find({"avatar": {"$exists": True}}).count()
```
