### ISSUE TITLE
API: timeline normalization error

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#533]
> User OID: 582457068740d9693650d173
> Method: GET
> URL: http://api.kdm-manager.com/settlement/get_summary/5839ffef8740d93fa4cb2743
> JSON: None
> 
```
Traceback (most recent call last):
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
 rv = self.dispatch_request()
File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
 return self.view_functions[rule.endpoint](**req.view_args)
File "/home/toconnell/kdm-manager-api/app/utils/crossdomain.py", line 56, in wrapped_function
 resp = flask.make_response(func(*args, **kwargs))
File "/home/toconnell/kdm-manager-api/app/routes.py", line 377, in collection_action
 asset_object = assets.get_user_asset(collection, asset_id)
File "/home/toconnell/kdm-manager-api/app/assets/__init__.py", line 86, in get_user_asset
 return settlements.Settlement(_id=asset_id)
File "/home/toconnell/kdm-manager-api/app/utils/__init__.py", line 239, in not_timed
 return method(*args, **kwargs)
File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 140, in __init__
 self.normalize()
File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 363, in normalize
 self.flatten_timeline_events()
File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 4042, in flatten_timeline_events
 new_event_group.append({'handle': event['handle']})
KeyError: 'handle'
```

**Comment by toconnell** [comment]
This...
```
192.168.0.116 - - [22/Jul/2019 14:26:53] "GET /settlement/get_summary/5839ffef8740d93fa4cb2743 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/home/toconnell/kdm-manager-api/app/utils/crossdomain.py", line 56, in wrapped_function
    resp = flask.make_response(func(*args, **kwargs))
  File "/home/toconnell/kdm-manager-api/app/__init__.py", line 118, in general_exception
    raise exception
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/toconnell/kdm-manager-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toconnell/kdm-manager-api/app/utils/crossdomain.py", line 56, in wrapped_function
    resp = flask.make_response(func(*args, **kwargs))
  File "/home/toconnell/kdm-manager-api/app/routes.py", line 377, in collection_action
    asset_object = assets.get_user_asset(collection, asset_id)
  File "/home/toconnell/kdm-manager-api/app/assets/__init__.py", line 86, in get_user_asset
    return settlements.Settlement(_id=asset_id)
  File "/home/toconnell/kdm-manager-api/app/utils/__init__.py", line 182, in timed
    result = method(*args, **kwargs)
  File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 140, in __init__
    self.normalize()
  File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 363, in normalize
    self.flatten_timeline_events()
  File "/home/toconnell/kdm-manager-api/app/models/settlements.py", line 4042, in flatten_timeline_events
    new_event_group.append({'handle': event['handle']})
KeyError: 'handle'
```

**Comment by toconnell** [comment]
This is fixed and will go out in the migration patch release:
```
diff --git a/app/models/settlements.py b/app/models/settlements.py
index 1aa15d3..931c74c 100644
--- a/app/models/settlements.py
+++ b/app/models/settlements.py
@@ -4033,15 +4033,20 @@ class Settlement(models.UserAsset):
             for event_group in y.keys():
                 if event_group != 'year':
                     new_event_group = []
-                    for event in y[event_group]:
-                        # if we have a 'name' and not a 'handle'
-                        if event.get('name', None) is not None and event.get('handle', None) is None:
-#                            self.logger.debug("OK %s" % event)
-                            new_event_group.append(event)
-                        else:
-                            new_event_group.append({'handle': event['handle']})
-#                            self.logger.debug("UPDATED: %s" % event)
-                    new_year[event_group] = new_event_group
+                    try:
+                        for event in y[event_group]:
+                            # if we have a 'name' and not a 'handle', prefer it
+                            if event.get('name', None) is not None and event.get('handle', None) is None:
+                                new_event_group.append(event)
+                            else:
+                                new_event_group.append(
+                                    {'handle': event['handle']}
+                                )
+                        new_year[event_group] = new_event_group
+                    except KeyError as e:
+                        err = 'Timeline event could not be migrated! %s' % event
+                        self.logger.exception(e)
+                        self.logger.error(err)
                 else:
                     new_year['year'] = y['year']
             new_timeline.append(new_year)
```
